algorithm: mcts-pw
use_dnn: False
mode: train
num_iter: 10000
num_es: 15
num_clusters: 5
num_devices_per_cluster: 5
message: ""
cpu_capacity: 13e9
max_pw_floor: 20
discount_factor: 0.1
optimize_for: latency