algorithm: mcts
mode: train
num_iter: 100000
num_es: 4
num_clusters: 1
num_devices_per_cluster: 20
message: "The most servere shit ever run"
cpu_capacity: 19.14e9
has_max_threshold: True
max_pw_floor: 100
discount_factor: 0.1
use_dnn: True